config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tweets/:tweet_id/likes' => 'likes#create'#追記
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'#追記
  resources :tweets
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
 end
 root 'tweets#index'
 resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
 belongs_to :user
 has_one_attached :image
  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
 has_many :comments, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  has_one_attached :image 
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
        if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
        #部分検索
        @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%')
      end
      if params[:tag_ids]
       @tweets = []
       params[:tag_ids].each do |key, value|      
        @tweets += Tag.find_by(name: key).tweets if value == "1"
       end
       @tweets.uniq!
      end
      
    if params[:tag]
      Tag.create(name: params[:tag])
    end
 end

 def new
    @tweet = Tweet.new
 end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id 
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
  end

  # 追加ここから
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :image, tag_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Oshikatsutalk" %></title>
    <link href="https://fonts.googleapis.com/css2?family=Train+One&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4d3619e3f9.js" crossorigin="anonymous"></script>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
 <header>
  <h1>Oshikatsutalk</h1>
  <div class="header-list">
   <ul>
     <li><%= link_to "ホーム", tweets_path %></li>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
 <footer>
      <p>Copyright © Oshikatsutalk All Rights Reserved.</p>
    </footer>
</body>

</html>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="header-main">
  <div class="slider">
    <% 3.times do %>
      <%= image_tag "IMG_3129.png" %>
      <%= image_tag "IMG_3130.png" %>
      <%= image_tag "IMG_3131.png" %>
      <%= image_tag "IMG_3132.png" %>
    <% end %>
  </div>
  <h1 class="catchcopy">誰でも推しが見つかる、推し活を応援します。</h1>
</div>
<div class="tweets-container">
<!--ここから-->
<div class="search-card">
<h3>投稿を検索</h3>
 <%= form_tag tweets_path, method: :get do %>
    <%= text_field_tag :search, nil, placeholder: "キーワード検索" %>
    <%= submit_tag "検索" %>
   </div>
   <% end %>
</div>
<!--ここまで-->
<div class="search-card">
<h3>タグで探す</h3>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <div class="tag-list">
     <% Tag.all.each do |t| %>
        <%= check_box_tag "tag_ids[#{t.name}]", "1" %>
        <span><%= t.name %></span> 
        </label>
    <% end %>
    </div>
    <div class="tag-submit">
      <%= submit_tag "検索" %>
    </div>
  <% end %>
</div>
<div class="search-card">
 <h3>タグを追加</h3>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
</div>
  <% end %>
</div>
<br>
<br>
<br>
<div class="top-buttons">
 <%= link_to "新規投稿", new_tweet_path %>
 
 <% if user_signed_in? %>
   <%= link_to "マイページ", user_path(current_user.id) %>
   <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %> 
 <% end %>
</div>
<h3>oshikatsu一覧</h3>
  
     <% @tweets.each do |t| %>
      <div class="tweet">
       <div class="main-box">
        <div class="name-container">
        <% if t.user.image.attached? %>
        <%= image_tag  t.user.image, size: '50x50'%>
        <%= link_to t.user.name, user_path(t.user.id) %> 
      </div>
        <div class="left-container">
        <%= t.body %>
      </div>
        <% if t.image.attached? %>
            <%= image_tag t.image, size: '100x100'%>
        <% end %>
        <% end %>
        <div class="right-container">
      
     <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
           <i class="fas fa-heart"></i><%= t.likes.count %>
      <% end %>
      <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
      <% end %>
  <% else %>
       
        <i class="far fa-heart"></i><%= t.likes.count %>
        
    <% end %>
        <%= t.created_at %>
        <%= link_to "詳細", tweet_path(t.id) %>
        <%= button_to "削除", tweet_path(t.id), method: :delete %>
      </div>
    </div>
    
 </div>
<% end %>

app/views/tweets/new.html.erb
<h1>(oshikatsutalk)</h1>
<h3>新規oshikatsu投稿ページ</h3>
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
     <br>
        <%= f.text_field :body, size: 140%>
      <br>
 <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
  </div>
   <!-- ここまで -->

  <%= f.submit "投稿" %>
  <br>
 <% end %>
</div>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<br>
<br>
<br>

app/views/tweets/show.html.erb
<h1>Oshikatsutalk</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
          <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
         <i class="far fa-heart"></i>
        　<span><%= @tweet.likes.count %></span>
        <% end %>
      <% end %>
    <% else %>
     <i class="far fa-heart"></i><%= @tweet.likes.count %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li>
   <%= link_to user.name, user_path(user) %>
  </li>
<% end %>
<div class="comment-wrapper">
<h2>コメント一覧</h2>
  <div class="comment-list">
   <% @comments.each do |c| %>
    <div class="comment-row <%= 'my-comment-row' if c.user == current_user %>">
    
    <div class="comment-avatar">
      <% if c.user.image.attached? %>
        <%= image_tag c.user.image, class: "avatar" %>
      <% else %>
       <%= image_tag "default_icon.png", class: "avatar" %>
      <% end %>
    </div>
    
    <div class="comment-box <%= 'my-comment' if c.user == current_user %>">
          <div class="comment-name">
           <%= link_to c.user.name, user_path(c.user) %>
          </div>
          <div class="comment-content">
            <%= c.content %>
          </div>
        </div>

      </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>
<br>
<br>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<br>
<br>
<br>
<br>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <br>
<%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 <br>
<%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->

<% if @user.image.attached? %>
     <%= image_tag  @user.image, class: "avatar", size: '50x50'%>
<% else %>
  <%= image_tag "default_icon.png", class: "avatar" %>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>